# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setPointSize(14)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/res/goodFish.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(46, 46))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDBIndex = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("数据库视图")
        self.actionDBIndex.setIcon(icon)
        self.actionDBIndex.setObjectName("actionDBIndex")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/res/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon1)
        self.actionSearch.setObjectName("actionSearch")
        self.actionSetUp = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/res/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetUp.setIcon(icon2)
        self.actionSetUp.setObjectName("actionSetUp")
        self.actionIndexDB = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/png/res/gallery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIndexDB.setIcon(icon3)
        self.actionIndexDB.setObjectName("actionIndexDB")
        self.toolBar.addAction(self.actionIndexDB)
        self.toolBar.addAction(self.actionSearch)
        self.toolBar.addAction(self.actionSetUp)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "陈三五娘数据库"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDBIndex.setText(_translate("MainWindow", "DataBaseHomePage"))
        self.actionDBIndex.setIconText(_translate("MainWindow", "DBIndex"))
        self.actionDBIndex.setToolTip(_translate("MainWindow", "数据起始页"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionSearch.setToolTip(_translate("MainWindow", "数据库检索"))
        self.actionSetUp.setText(_translate("MainWindow", "SetUp"))
        self.actionSetUp.setToolTip(_translate("MainWindow", "设置"))
        self.actionIndexDB.setText(_translate("MainWindow", "IndexDB"))
        self.actionIndexDB.setToolTip(_translate("MainWindow", "数据库起始页"))
import UI.c35n_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
