# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_DBTreeMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBTreeMain(object):
    def setupUi(self, DBTreeMain):
        DBTreeMain.setObjectName("DBTreeMain")
        DBTreeMain.resize(714, 365)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DBTreeMain)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tree_LeftView = QtWidgets.QTreeWidget(DBTreeMain)
        self.tree_LeftView.setObjectName("tree_LeftView")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_LeftView)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.tree_LeftView.header().setVisible(False)
        self.horizontalLayout.addWidget(self.tree_LeftView)
        self.widget_RightView = QtWidgets.QWidget(DBTreeMain)
        self.widget_RightView.setObjectName("widget_RightView")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_RightView)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_RightView = QtWidgets.QVBoxLayout()
        self.layout_RightView.setObjectName("layout_RightView")
        self.horizontalLayout_2.addLayout(self.layout_RightView)
        self.horizontalLayout.addWidget(self.widget_RightView)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 10)

        self.retranslateUi(DBTreeMain)
        QtCore.QMetaObject.connectSlotsByName(DBTreeMain)

    def retranslateUi(self, DBTreeMain):
        _translate = QtCore.QCoreApplication.translate
        DBTreeMain.setWindowTitle(_translate("DBTreeMain", "Form"))
        __sortingEnabled = self.tree_LeftView.isSortingEnabled()
        self.tree_LeftView.setSortingEnabled(False)
        self.tree_LeftView.topLevelItem(0).setText(0, _translate("DBTreeMain", "陈三五娘文献数据库"))
        self.tree_LeftView.topLevelItem(0).child(0).setText(0, _translate("DBTreeMain", "现代研究文献"))
        self.tree_LeftView.topLevelItem(0).child(0).child(0).setText(0, _translate("DBTreeMain", "期刊"))
        self.tree_LeftView.topLevelItem(0).child(0).child(0).setText(1, _translate("DBTreeMain", "0"))
        self.tree_LeftView.topLevelItem(0).child(0).child(1).setText(0, _translate("DBTreeMain", "图书"))
        self.tree_LeftView.topLevelItem(0).child(0).child(1).setText(1, _translate("DBTreeMain", "1"))
        self.tree_LeftView.topLevelItem(0).child(0).child(2).setText(0, _translate("DBTreeMain", "学位论文"))
        self.tree_LeftView.topLevelItem(0).child(0).child(2).setText(1, _translate("DBTreeMain", "2"))
        self.tree_LeftView.topLevelItem(0).child(0).child(3).setText(0, _translate("DBTreeMain", "会议论文"))
        self.tree_LeftView.topLevelItem(0).child(0).child(3).setText(1, _translate("DBTreeMain", "3"))
        self.tree_LeftView.topLevelItem(0).child(1).setText(0, _translate("DBTreeMain", "民间原始文献（手抄本）"))
        self.tree_LeftView.topLevelItem(0).child(1).child(0).setText(0, _translate("DBTreeMain", "戏曲"))
        self.tree_LeftView.topLevelItem(0).child(1).child(0).setText(1, _translate("DBTreeMain", "4"))
        self.tree_LeftView.topLevelItem(0).child(1).child(1).setText(0, _translate("DBTreeMain", "歌册"))
        self.tree_LeftView.topLevelItem(0).child(1).child(1).setText(1, _translate("DBTreeMain", "5"))
        self.tree_LeftView.topLevelItem(0).child(1).child(2).setText(0, _translate("DBTreeMain", "南音曲谱"))
        self.tree_LeftView.topLevelItem(0).child(1).child(2).setText(1, _translate("DBTreeMain", "6"))
        self.tree_LeftView.setSortingEnabled(__sortingEnabled)
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBTreeMain = QtWidgets.QWidget()
    ui = Ui_DBTreeMain()
    ui.setupUi(DBTreeMain)
    DBTreeMain.show()
    sys.exit(app.exec_())
