# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ReadPDF.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetReadPDF(object):
    def setupUi(self, widgetReadPDF):
        widgetReadPDF.setObjectName("widgetReadPDF")
        widgetReadPDF.resize(600, 400)
        widgetReadPDF.setMinimumSize(QtCore.QSize(600, 400))
        widgetReadPDF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(widgetReadPDF)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(widgetReadPDF)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.actionSaveAs = QtWidgets.QToolButton(self.widget)
        self.actionSaveAs.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.horizontalLayout.addWidget(self.actionSaveAs)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.actionPrint = QtWidgets.QToolButton(self.widget)
        self.actionPrint.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon1)
        self.actionPrint.setObjectName("actionPrint")
        self.horizontalLayout.addWidget(self.actionPrint)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showArea = QtWidgets.QScrollArea(widgetReadPDF)
        self.showArea.setWidgetResizable(True)
        self.showArea.setObjectName("showArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 476, 350))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.showArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.showArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_FileStatus = QtWidgets.QLabel(widgetReadPDF)
        self.label_FileStatus.setObjectName("label_FileStatus")
        self.horizontalLayout_2.addWidget(self.label_FileStatus)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(widgetReadPDF)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 10)

        self.retranslateUi(widgetReadPDF)
        QtCore.QMetaObject.connectSlotsByName(widgetReadPDF)

    def retranslateUi(self, widgetReadPDF):
        _translate = QtCore.QCoreApplication.translate
        widgetReadPDF.setWindowTitle(_translate("widgetReadPDF", "Form"))
        self.label_FileStatus.setText(_translate("widgetReadPDF", "TextLabel"))
        self.label.setText(_translate("widgetReadPDF", "Ctrl+鼠标滚轮调整页面大小"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetReadPDF = QtWidgets.QWidget()
    ui = Ui_widgetReadPDF()
    ui.setupUi(widgetReadPDF)
    widgetReadPDF.show()
    sys.exit(app.exec_())
