# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TraditionalOperaDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TraditionalOperaDetail(object):
    def setupUi(self, TraditionalOperaDetail):
        TraditionalOperaDetail.setObjectName("TraditionalOperaDetail")
        TraditionalOperaDetail.resize(288, 399)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(TraditionalOperaDetail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(TraditionalOperaDetail)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_Title = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.horizontalLayout_2.addWidget(self.lineEdit_Title)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_Author = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Author.setObjectName("lineEdit_Author")
        self.horizontalLayout_3.addWidget(self.lineEdit_Author)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_Pages = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Pages.setObjectName("lineEdit_Pages")
        self.horizontalLayout_4.addWidget(self.lineEdit_Pages)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_Origin = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Origin.setObjectName("lineEdit_Origin")
        self.horizontalLayout_5.addWidget(self.lineEdit_Origin)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_Summary = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_Summary.setObjectName("textEdit_Summary")
        self.horizontalLayout.addWidget(self.textEdit_Summary)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.setStretch(0, 9)

        self.retranslateUi(TraditionalOperaDetail)
        QtCore.QMetaObject.connectSlotsByName(TraditionalOperaDetail)

    def retranslateUi(self, TraditionalOperaDetail):
        _translate = QtCore.QCoreApplication.translate
        TraditionalOperaDetail.setWindowTitle(_translate("TraditionalOperaDetail", "Form"))
        self.groupBox_2.setTitle(_translate("TraditionalOperaDetail", "戏曲信息"))
        self.label.setText(_translate("TraditionalOperaDetail", "戏曲名："))
        self.label_2.setText(_translate("TraditionalOperaDetail", "作  者："))
        self.label_3.setText(_translate("TraditionalOperaDetail", "页码："))
        self.label_4.setText(_translate("TraditionalOperaDetail", "收录来源："))
        self.groupBox.setTitle(_translate("TraditionalOperaDetail", "简介"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TraditionalOperaDetail = QtWidgets.QWidget()
    ui = Ui_TraditionalOperaDetail()
    ui.setupUi(TraditionalOperaDetail)
    TraditionalOperaDetail.show()
    sys.exit(app.exec_())
